### PR TITLE
nexd: fixes #1246 - fallback to using wireguard-go on linux

### LINKED ISSUE #1246: Can't run nexd on a OCP 4.12.16 cluster
### Describe the bug

Reported at:
see https://discord.com/channels/1097686137855819866/1097686139411910669/1125773179495907378

Error is:
```{"level":"error","caller":"nexodus/nexodus_linux.go:33","msg":"failed to create the ip link interface: failed to run \"ip link add wg0 type wireguard\": exit status 2 (Error: Unknown device type.\n)\n"}```

It is suspected that the wg driver is missing from the linux kernel.

### How to Reproduce

Run on linux kernel without wg suport

### Expected Behavior

We should still run, with wireguard-go.

### Deployment Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
@russellb @nerdalert can you guys think of way to test this?  Maybe some cli flag or env to force the fallback option?

**Comment by russellb** [comment]
> @russellb @nerdalert can you guys think of way to test this? Maybe some cli flag or env to force the fallback option?

Yes, an env var (not a command line argument) seems reasonable to me.

**Review by sridhargaddam — APPROVED** [review]
Verified the PR on an OCP 4.12.16 cluster setup (where the wireguard kernel modules were not present on the node) and confirm that `wg0` interface gets created properly and datapath works fine.

Thanks @chirino

**Review by nerdalert — APPROVED** [review]
LGTM @sridhargaddam ty for validating the patch!

**Pull request merged**
