### PR TITLE
nexd: Move run code into its own function

### PR DESCRIPTION
**Pull request by russellb**
This moves the run code into its own function that can be
    paramterized. This will be used when adding subcommands that alter the
    behavior.
    
    Also remove some code that was a placeholder and never implemented.
    This cleanup probably belongs elsewhere anyway. It's going to be
    dependent on the mode nexd is running in, the OS, and eventually the
    tunneling mechanism.

### CODE REVIEW

**Comment by nerdalert** [comment]
@russellb  @vishnoianil what are examples of other options that will be going instead of agent? I'm guessing something denoting relay? Ty.

```
nexd agend CMD
nexd ??? CMD
nexd ??? CMD
```

**Comment by russellb** [comment]
> @russellb @vishnoianil what are examples of other options that will be going instead of agent? I'm guessing something denoting relay? Just want to understand the justification for adding a parameter for a pretty default value. Ty!
> 
> ```
> nexd agent CMD
> nexd ??? CMD
> nexd ??? CMD
> ```
https://docs.nexodus.io/development/design/userspace-mode/#cli-subcommands

```
nexd agent
nexd proxy
... and presumably ...
nexd relay
```

**Comment by russellb** [comment]
I'm breaking up some of what's neeed for my `nexd proxy` PR. This seemed standalone enough to push by itself.

**Comment by vishnoianil** [comment]
@nerdalert I was thinking on the same line as @russellb mentioned above

```
 nexd 
	agent
		controller-url
		username
		password
		public-key
		private-key
		listen-port
		request-ip
		local-endpoint-ip
		child-prefix
		stun
		insecure-skip-tls-verify
	relay
		enable-discovery (replacement of --discovery-node)
	proxy
		option1
```

Alternative I was considering was to make "agent" subcommand implicit here, something like 

```
 nexd
       GLOBAL_OPTION
              controller-url
              username
              password
              public-key
              private-key
              listen-port
              request-ip
              local-endpoint-ip
              child-prefix
              stun
              insecure-skip-tls-verify
	relay
		enable-discovery (replacement of --discovery-node)
	proxy
		option1
```

I am okay both ways, @russellb @nerdalert wdyt?

**Comment by nerdalert** [comment]
I like @vishnoianil proposal of:

```
 nexd
       GLOBAL_OPTION
              controller-url
              username
              password
              public-key
              private-key
              listen-port
              request-ip
              local-endpoint-ip
              child-prefix
              stun
              insecure-skip-tls-verify
	relay
		enable-discovery (replacement of --discovery-node)
	proxy
		option1
```

That ticks my box of preserving :

```
nexd  https://try.nexodus.local
```

Good either way but that would me my fav.

**Comment by russellb** [comment]
ACK - thanks for the feedback!  I'll mark it as a draft while I work on another revision.

**Comment by russellb** [comment]
I ended up abandoning subcommand changes because it's too tangled. Instead this now only includes a minor change to split out the run function so it can be paramterized in future commits.

**Review by nerdalert — APPROVED** [review]
LGTM!

**Review by vishnoianil — APPROVED** [review]

**Review by chirino — COMMENTED** [review]
lgtm

**Pull request merged**
