### PR TITLE
Trim stun server list to prevent an empty string being returned

### PR DESCRIPTION
**Pull request by nerdalert**
- resolves getting an empty string as a stun server

### CODE REVIEW

**Comment by nerdalert** [comment]
Resolves an issue of getting empty stun servers. You might have noticed it with warn messages like this on Linux nodes:

```
WARN	nexodus/nexodus.go:229	transaction error: write ip 0.0.0.0->:0: sendmsg: destination address required
```

**Review by russellb — APPROVED** [review]
good catch

**Review by chirino — APPROVED** [review]
lgtm

**Comment by chirino** [comment]
@nerdalert rebased off main for ya.

**Pull request merged**
