### PR TITLE
Add the option to disable security groups at runtime

### PR DESCRIPTION
**Pull request by nerdalert**

### CODE REVIEW

**Comment by vishnoianil** [comment]
LGTM

**Review by russellb — COMMENTED** [review]
Do you see a use case for this if API performance was not a concern?

**Comment by nerdalert** [comment]
> Do you see a use case for this if API performance was not a concern?

I do in the scenario a user didn't want to install the nftables userspace tool until we migrate that to kernel api calls.

**Comment by russellb** [comment]
> > Do you see a use case for this if API performance was not a concern?
> 
> @russellb good point! I do in the scenario a user didn't want to install the nftables userspace tool until we migrate that to kernel api calls. That said Im not super attached to it or anything if you think its overthinking things.

It feels weird to offer "turn security off." I feel like if policy is defined, we should enforce it or fail.

If it's for dev/test use cases, then I'd be ok with it as a hidden option.

**Pull request closed without merging**
