### PR TITLE
bump: the grafana version to v5.0.0-rc1

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by dave-tucker** [comment]
Why do we need to use the v5 RC?

**Comment by chirino** [comment]
@dave-tucker mentioned we can't upgrade the version used in our clusters.. so closing for now.

**Comment by chirino** [comment]
Looks like grafana is not installed in the qa/prod env anyways.

**Review by dave-tucker — CHANGES_REQUESTED** [review]

**Comment by dave-tucker** [comment]
I've rolled this into #910 so will close this one for now.

**Pull request closed without merging**
