### PR TITLE
Add e2e coverage for nexctl socket status

### PR DESCRIPTION
**Pull request by nerdalert**
- Replaces sleeps for discovery node joins with nexctl nexd status

### CODE REVIEW

**Comment by nerdalert** [comment]
@chirino refresh me if you added e2e support for OSX. If so this breaks it since socket status isn't supported on OSX yet. Can put this on the back burner if so.

**Comment by chirino** [comment]
Not yet

**Comment by nerdalert** [comment]
@chirino I deleted the comment after thinking through it and its being executed in the container it shouldn't break OSX. Ty!

**Review by russellb — APPROVED** [review]
Nice one, Brent! This lgtm. I have a couple little ideas, but I'll post them as a follow up.

**Comment by russellb** [comment]
> Nice one, Brent! This lgtm. I have a couple little ideas, but I'll post them as a follow up.

This is what I was thinking about: https://github.com/nexodus-io/nexodus/pull/579

The `CheckPeriodically()` helper didn't reduce the size of the code as much as I thought, but it still seemed like a useful pattern to put in a helper.

**Pull request merged**
